apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  vsphereVolume:
    volumePath: "[vsanDatastore] pks_sandbox_disk/myDisk"
    fsType: ext4
