---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low
value: 1000
globalDefault: true
description: "This priority class should be used for test pods only."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high
value: 300000
globalDefault: false
description: "This priority class should be used for development pods only."
