---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  username: c2NodWx1bmc=
  password: ZW5lcmd5Mm1hcmtldA==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never
